Import('env')
from Component import Component

name = "example_data"
data =  env.Dir("data")
dependencies = [ ]
incPath = []
lib = []

builtData = env.Data([data])

d = env.RSync(env.Dir("$INSTALL_DIR/example/data/"), data)
env.Depends(d, builtData)
env.AlwaysBuild(d)
ali = env.Alias("@example_data", d)

env.AddComponent(name, None, incPath, lib, dependencies)

