Import('env')

name = "voxel"
incPath = [env.Dir("#/lib/"+name)]
dependencies = ['renderer']

env.Append(CPPPATH=incPath)
src_files = env.Glob("*.cpp")
lib = env.KStaticLibrary(name, src_files, dependencies)
env.AddComponent(name, None, incPath, lib, dependencies)

