Import('env')


#dependencies = ['Voxel']
dependencies = ['Renderer']

src_files = env.Glob("src/*.cpp")
prog = env.KProgram("Kinevox", src_files, dependencies)
finalProduct = env.Install(env.Dir("$INSTALL_DIR"), prog)

Default(finalProduct)