Import('env')


#dependencies = ['voxel']
dependencies = ['renderer']

src_files = env.Glob("src/*.cpp")
prog = env.KProgram("kinevox", src_files, dependencies)
finalProduct = env.Install(env.Dir("$INSTALL_DIR"), prog)

Default(finalProduct)