Import('env')



dependencies = ['applayer', 'example_data']

src_files = env.Glob("src/*.cpp")
prog = env.KProgram("spriteExample", src_files, dependencies)
finalProduct = env.Install(env.Dir("$INSTALL_DIR/example"), prog)
env.Alias("@SpriteExample",finalProduct) 
env.Depends(env.Alias("@SpriteExample"), env.Alias("@example_data"))
env.Alias("@examples", env.Alias("@Mesh"))
Default(finalProduct)