#Copyright (C) 2011 by Francois Coulombe

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
# 

Import('env')

name = "script"
incPath = [env.Dir("#/lib/"+name), env.Dir("#lib/"+name+"/lua-5.2.1/src")]
dependencies = ['gcl']
cflags = ['-DLUA_COMPAT_ALL'] #, '-DLUA_ANSI']
disabledWarnings = ['/wd 4702', '/wd 4244', '/wd 4324', '/wd 4334', '/wd 4146', '/wd 4267']


env.AppendUnique(CPPFLAGS=cflags)
env.AppendUnique(CXXFLAGS=cflags)
env.AppendUnique(CFLAGS=cflags)

env.AppendUnique(CPPFLAGS=disabledWarnings)
env.AppendUnique(CXXFLAGS=disabledWarnings)
env.AppendUnique(CFLAGS=disabledWarnings)


env.Append(CPPPATH=incPath)
src_files = env.Glob("*.cpp")
lua_src_files = env.Glob("lua-5.2.1/src/*.c")
src_files.extend(lua_src_files)
lib = env.KStaticLibrary(name, src_files, dependencies)
env.AddComponent(name, cflags, incPath, lib, dependencies)

