Import('env')

dependencies = ['common']
src_files = env.Glob("src/*.cpp")
data_files =[env.Dir("data")]


prog = env.KProgram("worldconverter", src_files, dependencies)
finalProduct = env.Install(env.Dir("$INSTALL_DIR/tools/world_converter"), prog)
a = env.Alias("@WorldConverter",finalProduct) 
env.Depends("@worldconverter", env.Alias("common_test_run")) #run the common test before to build the tools
env.Alias("@tools",a) 
