Import('env')

name = "AppLayer"
incPath = [env.Dir("#/lib/"+name)]
dependencies = ['Renderer', 'Input']

env.Append(CPPPATH=incPath)
src_files = env.Glob("*.cpp")
lib = env.KStaticLibrary(name, src_files, dependencies)
env.AddComponent(name, incPath, lib, dependencies)

