Import('env')



dependencies = ['applayer', 'example_data']

src_files = env.Glob("src/*.cpp")
prog = env.KProgram("spinningCube", src_files, dependencies)
finalProduct = env.Install(env.Dir("$INSTALL_DIR/example"), prog)
env.Alias("@Mesh",finalProduct) 
env.Depends(env.Alias("@Mesh"), env.Alias("@example_data"))
Default(finalProduct)