Import('env')

name = "input"
incPath = [env.Dir("#/lib/"+name)]
dependencies = ['gcl', 'sdl']

env.Append(CPPPATH=incPath)
src_files = env.Glob("*.cpp")
lib = env.KStaticLibrary(name, src_files, dependencies)
env.AddComponent(name, incPath, lib, dependencies)

