Import('env')



dependencies = ['applayer', 'example_data']

src_files = env.Glob("src/*.cpp")
prog = env.KProgram("basicTextureMapping", src_files, dependencies)
finalProduct = env.Install(env.Dir("$INSTALL_DIR/example"), prog)
env.Alias("@BasicTextureMapping",finalProduct) 
env.Depends(env.Alias("@BasicTextureMapping"), env.Alias("@example_data"))
env.Alias("@examples", env.Alias("@BasicTextureMapping"))
Default(finalProduct)