Import('env')

name = "Renderer"
incPath = [env.Dir("#/lib/"+name)]
dependencies = ['Kinect', 'GCL', 'SDL', 'OpenCV', 'OpenGL', 'IL', 'libpng']

env.Append(CPPPATH=incPath)
src_files = env.Glob("*.cpp")
lib = env.KStaticLibrary(name, src_files, dependencies)
env.AddComponent(name, incPath, lib, dependencies)

