Import('env')

name = "Kinect"
incPath = [env.Dir("#/lib/"+name)]
dependencies = ['Input','libfreenect']

                                
env.Append(CPPPATH=incPath)
src_files = env.Glob("*.cpp")
lib = env.KStaticLibrary(name, src_files, dependencies)
env.AddComponent(name, incPath, lib, dependencies)

