Import('env')

name = "Renderer_test"
dependencies = ["Renderer"]
data = [ env.Dir("data")]
print "path: %s" % data[0].abspath
src_files = env.Glob("*.cpp")
prog = env.UnitTest(name, src_files, dependencies, data)
